### ISSUE TITLE
 3.6.2節のspec/routingディレクトリが見つからないエラーと同様に、spec/controllersもエラーになる

### ISSUE THREAD

**Issue by yasulab** [yasslab/railstutorial.jp#15]
(Thanks @minamijoyo for reporting this.)
cf. https://twitter.com/minamijoyo/status/555309419999674368

**Comment by yasulab** [comment]
こちら解決しました (詳細は上記リンクから辿れる Twitter 上の会話を参照のこと) :white_check_mark:

**Comment by minamijoyo** [comment]
報告いただきありがとうございます。

本文の全部の変更を把握できていないので、「解決しました」の意味を掴みかねておるのですが、直接の該当箇所（3.6.2/8.2.1)の本文の記載が修正されているようには見えず、直近のコミットがカンマを修正していただけで本件とは無関係そうで、「解決しました」というのはなんらか前提条件が変わって、事象が発生しなくなったということでしょうか？

**Comment by yasulab** [comment]
Oh... すみません。Twitter上の最後のやり取りを見て見切り発車してしまいました :sweat_drops:色々とまとめて修正をコミットしちゃってるで既に直っている可能性もありますが、後ほど該当箇所を念のため確認しておきますね :bow: :sweat_drops:

**Comment by minamijoyo** [comment]
お手数おかけします:bow:

**Comment by yasulab** [comment]
直しました! (長い間お待たせしてしまってすみませんでした :sweat_drops: )

**Comment by minamijoyo** [comment]
対応ありがとうございました:bow:
