### ISSUE TITLE
6.1.3ユーザーオブジェクトを作成する

### ISSUE THREAD

**Issue by yui-knk** [yasslab/railstutorial.jp#17]
http://railstutorial.jp/chapters/modeling-users?version=4.0#sec-creating_user_objects

> User.newを引数なしで呼んだ場合は、すべての属性がnilのオブジェクトを返します。4.4.5では、オブジェクトの属性を設定するための初期化ハッシュ (hash) を引数に取るように、Userクラスの例 (user_example.rb) を設計しました。この設計は、同様の方法でオブジェクトを初期化するActive Recordの設計に基づいています。

の箇所ですが、`user_example.rb`は`example_user.rb`のことではないでしょうか？

**Comment by yasulab** [comment]
@yui-knk おぉ、その通りですね :sweat_drops: ご指摘ありがとうございます! さっそく修正させていただきました :star2:
